name: fitness_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.3
  file_picker: ^6.1.1
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  firebase_database: ^10.4.4
  firebase_storage: ^11.6.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.10
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appicon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
